Добавляет наставника
htmlacademy-htmlcss/2280491-device-36 pull request #1
Opened 2023-01-20 14:44 UTC by dornp

2023-01-21 13:49 UTC, Dima-Dim requested changes

2023-01-21 13:49 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`(https://htmlacademy.ru/profile/dima).
Сейчас это выглядит вот так:
https://github.com/htmlacademy-htmlcss/2280491-device-36/blob/a2689296b76b05b8b06d546ed516cebd3b343143/Readme.md
Нужно немного поправить чтобы ссылкой были имя и фамилия.

2023-01-21 14:58 UTC, dornp commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`(https://htmlacademy.ru/profile/dima).
Поправила

2023-01-23 03:35 UTC, Dima-Dim requested changes
В рамках текущего задания не должно быть добавления в проект каких либо других файлов. Всё лишнее нужно удалить.

2023-01-23 14:14 UTC, dornp commented
Убрала лишние изменения.

2023-01-23 14:22 UTC, merged