Завершаем вёрстку всех компонентов
htmlacademy-htmlcss/2280491-device-36 pull request #9
Opened 2023-03-03 14:10 UTC by dornp

2023-03-05 11:18 UTC, Dima-Dim requested changes

2023-03-05 11:18 UTC, Dima-Dim commented on catalog.html
> +                        <div class="catalog-opener-btn" type="button"></div>
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-03-05 11:18 UTC, Dima-Dim commented on index.html
> +                <button type="button">
Для скринридеров это кнопка с каким-то svg-кодом.

2023-03-05 11:18 UTC, Dima-Dim commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
Без br-а никак?

2023-03-05 11:18 UTC, Dima-Dim commented on index.html
> +                                    <button type="button"></button>
https://up.htmlacademy.ru/htmlcss/36/criteries#ALLY-02

2023-03-05 11:18 UTC, Dima-Dim commented on styles/styles.css
> +    top: 3.75px;
Точности до целых должно быть достаточно.

2023-03-05 18:50 UTC, dornp commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
В макете это новая строка, если не сделать перенос строки, то текст не будет соответствовать макету. Подскажи, какие ещё есть варианты?

2023-03-05 18:51 UTC, dornp commented on styles/styles.css
> +    top: 3.75px;
Я пробовала, у меня кружок в radio-button тогда не по центру. Поэтому я точно высчитала.

2023-03-06 07:04 UTC, Dima-Dim commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
Это должно было быть в демках. Ведь новая строка может образовываться не только от переноса, но и от того что ширины не хватило.

2023-03-06 11:23 UTC, dornp commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
Может сделать так?

Вы можете забрать товар сами, заехав в наш офис.`&emsp;`
Заодно сможете проверить работоспособность покупки.

2023-03-06 11:28 UTC, Dima-Dim commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
И так придётся делать каждый раз когда будет меняться текст? Искать то место где нужно сделать перенос? А если текста станет сильно больше? Почему не ограничить ширину блока чтобы он переносился автоматически?

2023-03-06 11:41 UTC, dornp commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
Если делать ширину блока как в макете, то тогда текст не переносится в нужном месте, поэтому приходится делать искусственный перенос строки. А если подгонять ширину каждого блока под текст, то тогда могут поехать другие блоки. Можно, конечно, подогнать ширину конкретно для этого блока, но тогда это выглядит странным, так как ширина блоков внутри родителя будет отличаться. Считается ли использование `<br>` или `&emsp;` ошибкой, или можем оставить так как есть?
<img width="1026" alt="Снимок экрана 2023-03-06 в 13 31 12" src="https://user-images.githubusercontent.com/104000652/223099453-10bf607d-647f-4ab0-afc1-0ab4d4f83a16.png">

2023-03-06 11:53 UTC, Dima-Dim commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
В целом подход с br возможен и используется, но я описал в какие моменты могу возникать проблемы. Можешь оставить так, если случайный проверяющий сделает замечание - поправишь.

2023-03-06 12:05 UTC, dornp commented on index.html
> +                        <br>Заодно сможете проверить работоспособность покупки.
Хорошо.

2023-03-07 15:16 UTC, merged